//
//  CurrencyExchangeViewController.swift
//  ExchangeTestApp
//
//  Created by Vladimir on 27.01.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CurrencyExchangeDisplayLogic: class
{
    func setNavigationTitle(viewModel: CurrencyExchange.SetNavigationTitle.ViewModel)
}

class CurrencyExchangeViewController: UIViewController, CurrencyExchangeDisplayLogic
{
    var contentView = CurrencyExchangeView()
    var interactor: CurrencyExchangeBusinessLogic?
    var router: (NSObjectProtocol & CurrencyExchangeRoutingLogic & CurrencyExchangeDataPassing)?
    
    // MARK: Object lifecycle
    
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?)
    {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }
    
    required init?(coder aDecoder: NSCoder)
    {
        super.init(coder: aDecoder)
        setup()
    }
    
    override func loadView()
    {
        view = contentView
    }
    
    private func setup()
    {
        let viewController = self
        let interactor = CurrencyExchangeInteractor()
        let presenter = CurrencyExchangePresenter()
        let router = CurrencyExchangeRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
        setupView()
    }
    
    override func viewDidLoad()
    {
        super.viewDidLoad()
        interactor?.getNavigationTitle(request: CurrencyExchange.SetNavigationTitle.Request())
    }
    
    private func setupView()
    {
        navigationItem.rightBarButtonItem = UIBarButtonItem(title: "Exchange", style: .plain, target: self, action: #selector(handleExchangeTaped))
    }
    
    @objc private func handleExchangeTaped() {
        print(1)
    }

}

extension CurrencyExchangeViewController {
    
    func setNavigationTitle(viewModel: CurrencyExchange.SetNavigationTitle.ViewModel)
    {
        navigationItem.title = viewModel.title
    }
}
