//
//  CurrencyExchangeInteractor.swift
//  ExchangeTestApp
//
//  Created by Vladimir on 27.01.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CurrencyExchangeBusinessLogic
{
    func getNavigationTitle(request: CurrencyExchange.SetNavigationTitle.Request)
}

protocol CurrencyExchangeDataStore
{
  //var name: String { get set }
}

class CurrencyExchangeInteractor: CurrencyExchangeBusinessLogic, CurrencyExchangeDataStore
{

    
  var presenter: CurrencyExchangePresentationLogic?
  var worker: CurrencyExchangeWorker?
  //var name: String = ""
  
  // MARK: Do something
  
//  func doSomething(request: CurrencyExchange.Something.Request)
//  {
//    worker = CurrencyExchangeWorker()
//    worker?.doSomeWork()
//
//    let response = CurrencyExchange.Something.Response()
//    presenter?.presentSomething(response: response)
//  }
}

extension CurrencyExchangeInteractor
{
    func getNavigationTitle(request: CurrencyExchange.SetNavigationTitle.Request) {
        presenter?.setNavigationTitle(responce: CurrencyExchange.SetNavigationTitle.Response(title: "€1.0 = €1.0"))
    }
}
