//
//  CurrencyExchangeModels.swift
//  ExchangeTestApp
//
//  Created by Vladimir on 27.01.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum CurrencyExchange
{
    // MARK: Use cases
    
    enum SetNavigationTitle
    {
        struct Request
        {
        }
        struct Response
        {
            var title: String
        }
        struct ViewModel
        {
            var title: String
        }
    }
    
    enum FetchCurrencies
    {
        struct Request
        {
        }
        struct Response
        {
            var currencies: [Currency]
        }
        struct ViewModel
        {
            var currencies: [Currency]
        }
    }
    
}
