//
//  CurrencyExchangeRouter.swift
//  ExchangeTestApp
//
//  Created by Vladimir on 27.01.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol CurrencyExchangeRoutingLogic
{
  //func routeToSomewhere(segue: UIStoryboardSegue?)
}

protocol CurrencyExchangeDataPassing
{
  var dataStore: CurrencyExchangeDataStore? { get }
}

class CurrencyExchangeRouter: NSObject, CurrencyExchangeRoutingLogic, CurrencyExchangeDataPassing
{
  weak var viewController: CurrencyExchangeViewController?
  var dataStore: CurrencyExchangeDataStore?
  
  // MARK: Routing
  
  //func routeToSomewhere(segue: UIStoryboardSegue?)
  //{
  //  if let segue = segue {
  //    let destinationVC = segue.destination as! SomewhereViewController
  //    var destinationDS = destinationVC.router!.dataStore!
  //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
  //  } else {
  //    let storyboard = UIStoryboard(name: "Main", bundle: nil)
  //    let destinationVC = storyboard.instantiateViewController(withIdentifier: "SomewhereViewController") as! SomewhereViewController
  //    var destinationDS = destinationVC.router!.dataStore!
  //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
  //    navigateToSomewhere(source: viewController!, destination: destinationVC)
  //  }
  //}

  // MARK: Navigation
  
  //func navigateToSomewhere(source: CurrencyExchangeViewController, destination: SomewhereViewController)
  //{
  //  source.show(destination, sender: nil)
  //}
  
  // MARK: Passing data
  
  //func passDataToSomewhere(source: CurrencyExchangeDataStore, destination: inout SomewhereDataStore)
  //{
  //  destination.name = source.name
  //}
}
